version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  
    steps:
      - checkout  
      - run:
          name: Instalacja zależności
          command: |
            python -m venv venv           
            . venv/bin/activate           
            pip install -r requirements.txt  
      - run:
          name: Uruchomienie testów
          command: |
            . venv/bin/activate           
            pytest                        
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
