version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  
    steps:
      - checkout  
      - run:
          name: Instalacja zależności
          command: |
            python -m venv venv           
            . venv/bin/activate           
            pip install -r requirements.txt  
      - run:
          name: Uruchomienie testów
          command: |
            . venv/bin/activate           
            pytest --maxfail=1 --disable-warnings --result-log=pytest_results.log 
      - store_test_results:
          path: pytest_results.log   

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
